### ISSUE TITLE
user に region を追加する

### ISSUE THREAD

**Issue by yuto-wl** [team-musashi/stamp-rally-firebase#31]
## 関連する Issue

- https://github.com/team-musashi/stamp-rally/issues/129

## 内容

user コレクションに region の項目を追加する

## 目的
スタンプラリーのソート機能を実装する

**Comment by nozomi-koborinai** [comment]
#30 のIssueをクローズしたらなぜかこのIssueまでクローズされてしまいました
このIssueは再オープンします
