### ISSUE TITLE
Firestore Security Rules の実装

### ISSUE THREAD

**Issue by nozomi-koborinai** [team-musashi/stamp-rally-firebase#6]
## 関連する Issue

- https://github.com/team-musashi/stamp-rally/issues/22

## 内容

- 下記Firestore DBに対応するセキュリティールールを実装するhttps://docs.google.com/presentation/d/1R7yuT1Q220tjR4CswzsXqlWc839BnaXnJJuyp3Rq8EQ/edit#slide=id.g18e62b32c75_1_0

**Comment by susatthi** [comment]
完了したのでクローズしやす
